#cloud-config
apt_update: true
# apt_upgrade: true
package_update: true
# package_upgrade: true

runcmd:
  # Create Folders
  - "mkdir -p /home/azureuser/.local/share /home/azureuser/snap/juju /home/azureuser/.kube"
  - "chown azureuser:azureuser /home/azureuser -R"

  # Install dependencies
  - "snap install jq"
  - "snap install kustomize"

  # Setup microk8s
  - "snap install microk8s --classic --channel=1.29/stable"
  - "usermod -a -G microk8s azureuser"
  - "microk8s enable dns hostpath-storage ingress metallb:10.64.140.43-10.64.140.49 rbac"
  - "microk8s status --wait-ready"
  - "snap alias microk8s.kubectl kubectl"
  - "microk8s config > /home/azureuser/.kube/config"
  - "chown azureuser:azureuser /home/azureuser/.kube -R"

  # Install juju
  - "su azureuser -c 'sudo snap install juju --channel=3.4/stable'"
  
  # Bootstrap Juju controller
  - "su azureuser -c 'juju add-k8s my-k8s --client'"
  - "su azureuser -c 'juju bootstrap my-k8s uk8sx'"

  # Deploy Kubeflow
  - "su azureuser -c 'juju add-model kubeflow'"
  - "su azureuser -c 'juju deploy kubeflow --trust --channel=1.8/stable'"

write_files:
  - path: /etc/sysctl.conf
    content: |
      fs.inotify.max_user_instances=1280
      fs.inotify.max_user_watches=655360

  - path: /home/azureuser/.bashrc
    content: alias kubectl=microk8s.kubectl

  - path: /home/azureuser/kubeflow-ingress.yaml
    owner: azureuser:azureuser
    content: |
      apiVersion: networking.k8s.io
      kind: Ingress
      metadata:
        name: istio-ingressgateway
      spec:
        rules:
        - host: 10.0.0.4.nip.io
          http:
            paths:
            - path: /
              backend:
                serviceName: istio-ingressgateway
                servicePort: 80