#cloud-config
apt_update: true
apt_upgrade: true
package_update: true
package_upgrade: true

packages:
  - jq
  - kubectl
  - kustomize

runcmd:
  # Install microk8s
  - "snap install microk8s --classic --channel=1.24/stable"
  #- "snap install microk8s --classic --channel=1.29/stable"
 
  # Add microk8s kubeconfig for azureuser
  - "su azureuser -c 'mkdir -p /home/azureuser/.kube && touch /home/azureuser/.kube/config'"
  - "microk8s config > /home/azureuser/.kube/config"
  - "snap alias microk8s.kubectl kubectl"
  - "usermod -a -G microk8s azureuser"
 
  # Enable microk8s addons
  - "microk8s enable dns hostpath-storage host-access ingress metallb:10.64.140.43-10.64.140.49"
  - "microk8s status --wait-ready"

  # Ensure the Juju home directory exists with correct permissions
  - "mkdir -p /home/azureuser/.local/share/juju"
  - "chown azureuser:azureuser /home/azureuser/.local -R"

  # Install Juju
  - "snap install juju --classic --channel=2.9/stable"
  - "su azureuser -c 'juju bootstrap microk8s'"
  # - "snap install juju --classic --channel=3.5/stable"
  # - "su azureuser -c 'juju add-k8s my-k8s --client'"
  # - "su azureuser -c 'juju bootstrap my-k8s uk8sx'"

  # Deploy Kubeflow
  - "su azureuser -c 'juju add-model kubeflow'"
  - "su azureuser -c 'juju deploy kubeflow --trust --channel=1.7/stable'"
  # - "su azureuser -c 'juju deploy kubeflow --trust --channel=1.8/stable'"

write_files:
  - path: /etc/sysctl.conf
    content: |
      fs.inotify.max_user_instances=1280
      fs.inotify.max_user_watches=655360

  - path: /home/azureuser/.bashrc
    content: alias kubectl=microk8s.kubectl

  - path: /home/azureuser/kubeflow-ingress.yaml
    content: |
      apiVersion: networking.k8s.io
      kind: Ingress
      metadata:
        name: istio-ingressgateway
      spec:
        rules:
        - host: 10.0.0.4.nip.io
          http:
            paths:
            - path: /
              backend:
                serviceName: istio-ingressgateway
                servicePort: 80